# $schema:https://json.schemastore.org/github-action.json
name: "Create a package repo for a single melange package"
description: "Create a package repo for a single melange package"

inputs:
  signing-key:
    description: "The private key used to sign the package index (PEM format)"
    required: false
    default: ""
  signing-key-name:
    description: "The name of the key used to sign the built packages (not including the .rsa/.rsa.pub suffix)"
    required: false
    default: ""

outputs:
  repo-dir:
    description: "Path to where the package repo was created"
    value: "${{ steps.mk-repo-dir.outputs.repo-dir }}"

runs:
  using: "composite"

  steps:
    - name: Create package repo directory
      id: mk-repo-dir
      shell: bash
      run: |
        set -euo pipefail
        
        REPO_DIR=$(mktemp -d --tmpdir="${RUNNER_TEMP}")
        
        echo "repo-dir=${REPO_DIR}" >> "${GITHUB_OUTPUT}"

    - name: Collect package versions
      shell: bash
      env:
        REPO_DIR: "${{ steps.mk-repo-dir.outputs.repo-dir }}"
      run: |
        set -euo pipefail

        SCRIPT="${GITHUB_ACTION_PATH}/collect-package-versions.sh"
        chmod +x "${SCRIPT}"
        "${SCRIPT}"

    - name: Build package index
      shell: bash
      env:
        REPO_DIR: "${{ steps.mk-repo-dir.outputs.repo-dir }}"
        SIGNING_KEY: "${{ inputs.signing-key }}"
        SIGNING_KEY_NAME: "${{ inputs.signing-key-name }}"
      run: |
        set -euo pipefail

        SCRIPT="${GITHUB_ACTION_PATH}/index-packages.sh"
        chmod +x "${SCRIPT}"
        "${SCRIPT}"
