# $schema:https://json.schemastore.org/github-action.json
name: "Create a package repo for a single melange package"
description: "Create a package repo for a single melange package"

inputs:
  repo-dir:
    description: "Path to where the package repo should be created"
    required: true
  signing-key:
    description: "The private key used to sign the package index (PEM format)"
    required: false
    default: ""
  signing-key-name:
    description: "The name of the key used to sign the built packages (not including the .rsa/.rsa.pub suffix)"
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Collect package versions
      shell: bash
      env:
        REPO_DIR: "${{ inputs.repo-dir }}"
      run: |
        set -euo pipefail

        SCRIPT="${GITHUB_ACTION_PATH}/collect-package-versions.sh"
        chmod +x "${SCRIPT}"
        "${SCRIPT}"

    - name: Build package index
      shell: bash
      env:
        REPO_DIR: "${{ inputs.repo-dir }}"
        SIGNING_KEY: "${{ inputs.signing-key }}"
        SIGNING_KEY_NAME: "${{ inputs.signing-key-name }}"
      run: |
        set -euo pipefail

        SCRIPT="${GITHUB_ACTION_PATH}/index-packages.sh"
        chmod +x "${SCRIPT}"
        "${SCRIPT}"
